name: Upload Files to MinIO S3 (BeautySyncPro)

on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS CLI for MinIO
      env:
        AWS_ACCESS_KEY_ID: fake-key
        AWS_SECRET_ACCESS_KEY: fake-secret
      run: |
        mkdir -p ~/.aws

        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

        echo "[default]" > ~/.aws/config
        echo "region = us-east-1" >> ~/.aws/config
        echo "output = json" >> ~/.aws/config

    - name: Create S3 Bucket (if not exists)
      run: |
        aws --endpoint-url http://localhost:9000 s3 mb s3://beautysyncpro || echo "Bucket may already exist"

    - name: Upload static files to S3
      run: |
        aws --endpoint-url http://localhost:9000 s3 sync static/ s3://beautysyncpro/static/

    - name: Upload templates to S3
      run: |
        aws --endpoint-url http://localhost:9000 s3 sync templates/ s3://beautysyncpro/templates/
